/// Makes DuckDB loadable from `flutter test` on the host machine.
///
/// `dart_duckdb` is a Flutter *plugin*: on a device the native library is
/// bundled by Gradle/CocoaPods. Under `flutter test` there is no bundle, so the
/// library has to be pointed at explicitly.
///
/// The package's own test-mode fallback looks in
/// `${Directory.current}/../duckdb/...`, which only resolves inside the
/// package's own repository — not for a consumer. And `Isolate.resolvePackageUri`
/// throws `Unsupported operation` under `flutter test`. So the package root is
/// read from `.dart_tool/package_config.json`, which is generated by
/// `pub get` and works on any machine and in CI without a hard-coded path.
library;

import 'dart:convert';
import 'dart:io';

import 'package:dart_duckdb/open.dart';
import 'package:dart_duckdb/src/api/open.dart' show OperatingSystem;
import 'package:path/path.dart' as p;

bool _configured = false;

/// Call once, before the first `duckdb.open()`, in a test's `setUpAll`.
void configureDuckDbForTests() {
  if (_configured) return;
  _configured = true;

  final packageRoot = _resolvePackageRoot('dart_duckdb');

  final (os, relative) = switch (Platform.operatingSystem) {
    'macos' => (OperatingSystem.macOS, 'macos/Libraries/release/libduckdb.dylib'),
    'linux' => (OperatingSystem.linux, 'linux/Libraries/release/libduckdb.so'),
    'windows' => (OperatingSystem.windows, 'windows/Libraries/release/duckdb.dll'),
    final other => throw UnsupportedError('No host DuckDB library for $other'),
  };

  final libPath = p.normalize(p.join(packageRoot, relative));
  if (!File(libPath).existsSync()) {
    throw StateError(
      'DuckDB native library not found at:\n  $libPath\n\n'
      'On macOS it is fetched by the CocoaPods prepare_command, so run\n'
      '  flutter build macos --debug\n'
      'once before running host tests.',
    );
  }

  open.overrideFor(os, libPath);
}

String _resolvePackageRoot(String packageName) {
  final configFile = File(
    p.join(Directory.current.path, '.dart_tool', 'package_config.json'),
  );
  if (!configFile.existsSync()) {
    throw StateError(
      'No .dart_tool/package_config.json — run `flutter pub get` first.',
    );
  }

  final config =
      jsonDecode(configFile.readAsStringSync()) as Map<String, dynamic>;
  final packages = (config['packages'] as List).cast<Map<String, dynamic>>();

  final entry = packages.firstWhere(
    (pkg) => pkg['name'] == packageName,
    orElse: () => throw StateError('$packageName is not in package_config.json'),
  );

  // rootUri is relative to the .dart_tool directory when not absolute.
  final rootUri = Uri.parse(entry['rootUri'] as String);
  if (rootUri.isAbsolute && rootUri.scheme == 'file') {
    return rootUri.toFilePath();
  }
  return p.normalize(
    p.join(configFile.parent.path, Uri.decodeFull(rootUri.toString())),
  );
}
